# Generated by Django 5.0.2 on 2025-07-27 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frauddetectionlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="image",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="is_fake",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="is_fraudulent",
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="detection_result",
            field=models.CharField(
                choices=[
                    ("authentic", "Authentic"),
                    ("deepfake", "Deepfake"),
                    ("uncertain", "Uncertain"),
                ],
                default="uncertain",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="facial_landmarks",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="file_name",
            field=models.CharField(default="unknown.mp4", max_length=255),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="file_type",
            field=models.CharField(default="video", max_length=10),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="frame_analysis",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="processing_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="technical_details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="temporal_consistency",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="threat_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="behavioral_analysis",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="detection_result",
            field=models.CharField(
                choices=[
                    ("legitimate", "Legitimate"),
                    ("suspicious", "Suspicious"),
                    ("fraudulent", "Fraudulent"),
                ],
                default="legitimate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="device_analysis",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="geolocation_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="processing_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="transaction_id",
            field=models.CharField(default="TXN-000000", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deepfakedetectionlog",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="frauddetectionlog",
            name="risk_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="frauddetectionlog",
            name="transaction_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OTPVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(default="123456", max_length=10)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("voice", "Voice Verification"),
                            ("sms", "SMS Verification"),
                            ("email", "Email Verification"),
                            ("biometric", "Biometric Verification"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                (
                    "verification_result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("blocked", "Blocked"),
                        ],
                        default="failed",
                        max_length=20,
                    ),
                ),
                ("voice_match_score", models.FloatField(blank=True, null=True)),
                ("attempt_count", models.IntegerField(default=1)),
                ("client_ip", models.GenericIPAddressField(default="127.0.0.1")),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("processing_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("deepfake_detected", "Deepfake Detected"),
                            ("voice_clone_detected", "Voice Clone Detected"),
                            ("fraud_attempt", "Fraud Attempt"),
                            ("failed_login", "Failed Login"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("account_locked", "Account Locked"),
                        ],
                        default="suspicious_activity",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(default="Security Alert", max_length=200)),
                ("message", models.TextField(default="Security alert detected")),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCloneDetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(default="unknown.wav", max_length=255)),
                ("file_type", models.CharField(default="audio", max_length=10)),
                ("file_size", models.IntegerField(default=0)),
                (
                    "detection_result",
                    models.CharField(
                        choices=[
                            ("authentic", "Authentic"),
                            ("clone", "Voice Clone"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("voice_biometrics", models.JSONField(default=dict)),
                ("spectral_analysis", models.JSONField(default=dict)),
                ("prosody_analysis", models.JSONField(default=dict)),
                ("processing_time", models.FloatField(default=0.0)),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
