# Generated by Django 5.0.2 on 2025-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_detectionlog"),
    ]

    operations = [
        # Update UserProfile model to match existing database schema
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ANALYST', 'Analyst')],
                default='USER',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(
                choices=[('FREEMIUM', 'Freemium'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')],
                default='FREEMIUM',
                max_length=20
            ),
        ),
    ]
