# Generated by Django 5.0.2 on 2025-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20250727_1557"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securityalert",
            name="user",
        ),
        migrations.RemoveField(
            model_name="voiceclonedetectionlog",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="deepfakedetectionlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Deepfake Detection Log",
                "verbose_name_plural": "Deepfake Detection Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="frauddetectionlog",
            options={
                "verbose_name": "Fraud Detection Log",
                "verbose_name_plural": "Fraud Detection Logs",
            },
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="detection_result",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="facial_landmarks",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="frame_analysis",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="technical_details",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="temporal_consistency",
        ),
        migrations.RemoveField(
            model_name="deepfakedetectionlog",
            name="threat_level",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="behavioral_analysis",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="detection_result",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="device_analysis",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="geolocation_data",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="processing_time",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="frauddetectionlog",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="analysis_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="deepfake_checks/"
            ),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="is_fake",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="source_type",
            field=models.CharField(
                choices=[("upload", "Upload"), ("screen_record", "Screen Recording")],
                default="upload",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deepfakedetectionlog",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="deepfake_videos/"),
        ),
        migrations.AddField(
            model_name="frauddetectionlog",
            name="is_fraudulent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deepfakedetectionlog",
            name="file_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.DeleteModel(
            name="OTPVerificationLog",
        ),
        migrations.DeleteModel(
            name="SecurityAlert",
        ),
        migrations.DeleteModel(
            name="VoiceCloneDetectionLog",
        ),
    ]
