# Generated by Django 5.0.2 on 2025-07-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_securityalert_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceDetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="voice_analysis/"
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[("live", "Live Recording"), ("upload", "File Upload")],
                        default="upload",
                        max_length=10,
                    ),
                ),
                ("is_cloned", models.BooleanField(default=False)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("authentic", "Authentic"),
                            ("cloned", "Cloned/Fake"),
                            ("suspicious", "Suspicious"),
                        ],
                        default="authentic",
                        max_length=20,
                    ),
                ),
                ("analysis_details", models.JSONField(blank=True, default=dict)),
                ("audio_duration", models.FloatField(default=0.0)),
                ("processing_time", models.FloatField(default=0.0)),
                ("sample_rate", models.IntegerField(default=44100)),
                ("bit_rate", models.IntegerField(default=128)),
                ("format", models.CharField(default="wav", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Detection Log",
                "verbose_name_plural": "Voice Detection Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
