# Generated by Django 5.0.2 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_voicedetectionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicedetectionlog",
            name="analysis_type",
            field=models.CharField(default="voice_clone_detection", max_length=50),
        ),
        migrations.AddField(
            model_name="voicedetectionlog",
            name="detected_language",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="voicedetectionlog",
            name="language_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="voicedetectionlog",
            name="language_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="voicedetectionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
